version: "3.7"
services:
  polardb-order:
    image: "postgres:13"
    container_name: "polardb-order"
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=polardb_order
  order-service:
    depends_on:
      - polardb-order
    image: "thomasvitale/order-service:0.0.1-SNAPSHOT"
    container_name: "order-service"
    ports:
      - 9002:9002
      - 8002:8002
    environment:
      # JVM environment variable to enable debug through a socket on port 8002
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8002
      - POLAR_BOOK_SERVICE_URL=http://192.168.87.131:9001
      - SPRING_DATASOURCE_URL=jdbc:postgresql://polardb-order:5432/polardb_order
